/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.myquiz.quiz1;

/**
 *
 * @author Fahim
 */
public class HomeUi extends javax.swing.JFrame {

    /**
     * Creates new form HomeUi
     */
    public HomeUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        btnMedium = new javax.swing.JButton();
        btnHard = new javax.swing.JButton();
        btnEasy = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(133, 168, 209));
        Title.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Title.setText("Select Level");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        btnMedium.setBackground(new java.awt.Color(133, 168, 209));
        btnMedium.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnMedium.setForeground(new java.awt.Color(10, 10, 10));
        btnMedium.setText("Medium");
        btnMedium.setMaximumSize(new java.awt.Dimension(120, 35));
        btnMedium.setMinimumSize(new java.awt.Dimension(120, 35));
        btnMedium.setPreferredSize(new java.awt.Dimension(120, 35));
        btnMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediumActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedium, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        btnHard.setBackground(new java.awt.Color(133, 168, 209));
        btnHard.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnHard.setForeground(new java.awt.Color(10, 10, 10));
        btnHard.setText("Hard");
        btnHard.setMaximumSize(new java.awt.Dimension(120, 35));
        btnHard.setMinimumSize(new java.awt.Dimension(120, 35));
        btnHard.setPreferredSize(new java.awt.Dimension(120, 35));
        btnHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHardActionPerformed(evt);
            }
        });
        getContentPane().add(btnHard, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        btnEasy.setBackground(new java.awt.Color(133, 168, 209));
        btnEasy.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEasy.setForeground(new java.awt.Color(10, 10, 10));
        btnEasy.setText("Easy");
        btnEasy.setMaximumSize(new java.awt.Dimension(120, 35));
        btnEasy.setMinimumSize(new java.awt.Dimension(120, 35));
        btnEasy.setPreferredSize(new java.awt.Dimension(120, 35));
        btnEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEasyActionPerformed(evt);
            }
        });
        getContentPane().add(btnEasy, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        btnExit.setBackground(new java.awt.Color(255, 153, 153));
        btnExit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(10, 10, 10));
        btnExit.setText("Exit");
        btnExit.setMaximumSize(new java.awt.Dimension(120, 35));
        btnExit.setMinimumSize(new java.awt.Dimension(120, 35));
        btnExit.setPreferredSize(new java.awt.Dimension(120, 35));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 80, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallhaven-exrqrr_1920x1080.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 500, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediumActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Medium().setVisible(true);
    }//GEN-LAST:event_btnMediumActionPerformed

    private void btnHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHardActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Hard().setVisible(true);
    }//GEN-LAST:event_btnHardActionPerformed

    private void btnEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEasyActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Easy().setVisible(true);
    }//GEN-LAST:event_btnEasyActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnEasy;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHard;
    private javax.swing.JButton btnMedium;
    // End of variables declaration//GEN-END:variables
}
