/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.myquiz.quiz1;

import javax.swing.JOptionPane;

/**
 *
 * @author Fahim
 */
public class Login_Page extends javax.swing.JFrame {

    /**
     * Creates new form Login_Page
     */
    public Login_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        reg_num = new javax.swing.JLabel();
        RegNum = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login Page");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(133, 168, 209));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_title.setText("Student Login");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, 38));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/uapLogo.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 50, -1, -1));

        txtPass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 160, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(133, 168, 209));
        jLabel1.setText("Password");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 80, 40));

        reg_num.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        reg_num.setForeground(new java.awt.Color(133, 168, 209));
        reg_num.setText("Registration No.");
        reg_num.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(reg_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 130, 40));

        RegNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegNumActionPerformed(evt);
            }
        });
        getContentPane().add(RegNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 160, 40));

        btn_login.setBackground(new java.awt.Color(178, 152, 212));
        btn_login.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_login.setForeground(new java.awt.Color(10, 10, 10));
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 340, 100, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallhaven-exrqrr_1920x1080.png"))); // NOI18N
        BG.setText("sdf");
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    boolean validPass = false;
    boolean validReg = false;
    
    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
        if(txtPass.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(Login_Page.this, "Enter your Password");
            txtPass.grabFocus();
            return;
        }
    }//GEN-LAST:event_txtPassActionPerformed

    private void RegNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegNumActionPerformed
        // TODO add your handling code here:
        if(RegNum.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(Login_Page.this, "Enter your Registration Number");
            RegNum.grabFocus();
            return;
        }
    }//GEN-LAST:event_RegNumActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        String username = RegNum.getText();
        String password = txtPass.getText();
        
        if(username.equals("22201037") && password.equals("1234fahim")) {
            setVisible(false);
            new HomeUi().setVisible(true);
            return;
        }
        else {
            JOptionPane.showMessageDialog(null, "Invalid Registration Number or Password");
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField RegNum;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel reg_num;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
